language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "pip install -r requirements.txt pep8 coverage coveralls"

script:
  - "nosetests -vv --with-timer --with-coverage --cover-package=gelato"

after_success:
  - coveralls